name: Docrot Detector
on: [push]

jobs:
  docrot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SuchiiJain/CS4485_Capstone@supabase-migration